#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & picom & 

bspc monitor -d       

bspc config border_width         1
bspc config window_gap           2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config single_monocle	 true
bspc config ignore_ewmh_focus	 true
bspc config external_rules_command

bspc config focused_border_color "#ffc1c6"
bspc config normal_border_color "#6c6364"

bspc rule -a Firefox desktop='^2' state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a flameshort manage=off
#bspc rule -a polybar state=sticky

#bspc rule -a '*' --one-shot ~/.config/bspwm/external_rules.sh


# Autostart app
bspc wm -O polybar

$HOME/.config/polybar/launch.sh

nitrogen --restore

